module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ["<rootDir>/src/setup-jest.ts"],
  globalSetup: 'jest-preset-angular/global-setup',
  moduleNameMapper: {
    "@app/(.*)": "<rootDir>/src/app/$1",
    "@assets/(.*)": "<rootDir>/src/assets/$1",
    "@core/(.*)": "<rootDir>/src/app/core/$1",
    "@env": "<rootDir>/src/environments/environment",
    "@src/(.*)": "<rootDir>/src/src/$1",
    "@services/(.*)": "<rootDir>/src/app/core/services/$1",
    "@helpers/(.*)": "<rootDir>/src/app/helpers/$1",
    "@shared/(.*)": "<rootDir>/src/app/shared/$1",
    '^src/(.*)$': '<rootDir>/src/$1'
  },
  collectCoverage: true,
  coverageDirectory: "./coverage/app",
  coverageReporters: ["lcov", "text-summary", "cobertura", "html", "json-summary", "json"],
  collectCoverageFrom: [
    "src/app/app.component.ts",
    "src/app/app.routes.ts",
    "src/app/guards/**/*.ts",
    "src/app/helpers/**/*.ts",
    "src/app/pages/**/*.ts",
    "src/app/services/**/*.ts",
    "src/app/interceptors/**/*.ts",
    "src/app/components/**/*.ts",
    "src/app/core/guards/**/*.ts",
    "src/app/core/services/hybrid-audit.service.ts",
    "src/app/core/services/hybrid-onboarding.service.ts",
    "src/app/core/models/error/HybridAdapterError.ts",
    "src/app/core/spi-impl/hybrid-key-storage.provider.ts",
    "src/app/features/hybrid-onboarding/hybrid-onboarding.page.ts",
    "src/app/features/signing/sign-prompt.component.ts",
    "src/app/features/hybrid-keymanager/hybrid-kdf.const.ts",
    "src/app/features/hybrid-keymanager/hybrid-key-enrollment.service.ts",
    "src/app/features/hybrid-keymanager/unwrap.service.ts",
    "src/app/features/hybrid-keymanager/sign.service.ts",
    "src/app/features/hybrid-keymanager/sign.api.ts",
    "src/app/core/services/activity.service.ts",
    "src/app/features/activity/activity.page.ts",
    "src/app/features/about/**/*.ts",
    "src/app/core/constants/support.constants.ts",
    // --- EUD-142: runtime UI translation ---
    "src/app/core/models/ui-text-translation.model.ts",
    "src/app/core/constants/ui-translation.constants.ts",
    "src/app/core/ports/translation-engine.port.ts",
    "src/app/core/adapters/browser-translator-engine.adapter.ts",
    "src/app/core/services/ui-translation-cache.service.ts",
    "src/app/core/services/ui-text-translation.service.ts",
    "src/app/core/services/telemetry.service.ts",
    "src/app/shared/helpers/ui-text-bundle.ts",
    "src/app/shared/services/user-preferences.service.ts",
    "src/app/features/language-selector/language-selector.page.ts",
  ],
  coveragePathIgnorePatterns: [
    '<rootDir>/node_modules/', 
    '<rootDir>/dist/',
  ],
  transformIgnorePatterns: ['/node_modules/(?!@stencil|stencil)/'],
  testPathIgnorePatterns: [
    '/node_modules/', 
    '/dist/',
    // '/src/app/main',
    // '/src/app/app.routes',
    // '/src/app/app.component',
    // '/src/app/components', 
    // '/src/app/guards',
    // '/src/app/helpers',
    // '/src/app/interceptors',
    // '/src/app/interfaces',
    // '/src/app/pages',
    // '/src/app/services'
  ]
};
